FROM karalabe/xgo-latest AS build
ARG VERSION=master

WORKDIR ${GOPATH}/src
RUN git clone --branch ${VERSION} https://github.com/google/cadvisor.git
WORKDIR ${GOPATH}/src/cadvisor
RUN xgo --targets=linux/386,linux/amd64,linux/arm-5,linux/arm-6,linux/arm-7,linux/arm64 .

FROM alpine

COPY --from=build /build /build
